apps/autoencoder/urls.py
from django.urls import path
from apps.autoencoder import views

app_name = 'autoencoder'

urlpatterns = [
    path('autoencode/', views.AutoEncodeView.as_view(), name='autoencode'),
    path('cases/', views.AutoEncodedCasesView.as_view(), name='cases')
]

apps/main/urls.py
from django.urls import path
from apps.main import views

app_name = 'main'

urlpatterns = [
    path('', views.MainView.as_view(), name='main')
]

apps/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from apps.users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout')
]

conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('autoencoder/', include('apps.autoencoder.urls', namespace='autoencoder')),
    path('', include('apps.users.urls', namespace='users')),
    path('', include('apps.main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

softarex_test/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

apps/autoencoder/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models


def validate_file_extension(value):
    if not value.name.endswith('.png'):
        raise ValidationError('You can upload only .png files')


class Case(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    original = models.ImageField(upload_to='cases/original/%Y/%m/%d', validators=[validate_file_extension])
    encoded = models.ImageField(upload_to='cases/encoded/%Y/%m/%d', null=True, validators=[validate_file_extension])

apps/autoencoder/forms.py
from django import forms
from django.core.files.images import ImageFile

from apps.autoencoder.autoencoder import Autoencoder
from apps.autoencoder.models import Case


class CreateCaseForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = ['original']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(CreateCaseForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        case = Case.objects.create(
            user=self.request.user,
            original=self.cleaned_data['original']
        )
        autoencoder = Autoencoder()
        encoded = autoencoder.predict(case.original.name)
        image = ImageFile(encoded, name='encoded.jpg')
        case.encoded = image
        case.save(update_fields=['encoded'])
        return case

apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import ModelForm


class UserUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ['username']

    def save(self, commit=True):
        username = self.cleaned_data['username']
        self.instance.username = username
        self.instance.save()
        return self.instance


class UserRegisterForm(ModelForm):
    password1 = forms.CharField(required=True)
    password2 = forms.CharField(required=True)
    error_messages = {
        "password_mismatch": "The two password fields didn’t match.",
        "username_exists": "User with this username already exists."
    }

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError(
                self.error_messages["username_exists"],
                code="username_exists",
            )
        return username

    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            raise ValidationError(
                self.error_messages["password_mismatch"],
                code="password_mismatch",
            )

    def save(self, commit=True):
        password = self.cleaned_data['password1']
        instance = super(UserRegisterForm, self).save(commit)
        instance.set_password(password)
        instance.save()
        return instance

apps/autoencoder/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView

from apps.autoencoder.forms import CreateCaseForm
from apps.autoencoder.models import Case
from apps.autoencoder.selectors import get_cases


class AutoEncodeView(LoginRequiredMixin, CreateView):
    template_name = 'autoencoder/autoencode.html'
    login_url = '/login/'
    success_url = reverse_lazy('autoencoder:cases')
    form_class = CreateCaseForm

    def get_form(self, form_class=None):
        return self.form_class(self.request.POST, self.request.FILES, request=self.request)


class AutoEncodedCasesView(LoginRequiredMixin, ListView):
    template_name = 'autoencoder/autoencode_cases.html'
    login_url = '/login/'
    model = Case

    def get_queryset(self):
        return get_cases(user=self.request.user)

apps/main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class MainView(LoginRequiredMixin, TemplateView):
    template_name = 'main.html'
    login_url = '/login/'

apps/users/views.py
from django.contrib.auth import views
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from apps.users.forms import UserRegisterForm, UserUpdateForm


class LoginView(views.LoginView):
    template_name = 'auth/login.html'

    def get_success_url(self):
        return '/'


class RegisterView(CreateView):
    template_name = 'auth/register.html'
    success_url = reverse_lazy('users:login')
    form_class = UserRegisterForm


class ProfileView(UpdateView):
    template_name = 'auth/profile.html'
    success_url = '/'
    form_class = UserUpdateForm

    def get_object(self, queryset=None):
        return self.request.user


class CustomLogoutView(LogoutView):
    next_page = '/login/'

templates/autoencoder/autoencode.html
{% extends 'base.html' %}
{% block title %}
    Auto-encode image
{% endblock %}
{% block head %}
    <style>
        .child {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
{% endblock %}
{% block content %}
    <div class="d-relative">
        <div class="card p-3 text-center child">
            <div class="card-head">
                <h3> Auto-encode image</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'autoencoder:autoencode' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="original">Your image</label>
                        <input accept=".png" type="file" id="original" name="original" class="form-control">
                        {% if form.errors %}
                            <ul class="mt-2">
                                {% for error in form.errors.original %}
                                    <li class="bg-light text-danger">
                                        {{ error }}
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                    <div class="form-group mt-2">
                        <a href="{% url 'main:main' %}" class="btn btn-warning">Cancel</a>
                        <button class="btn btn-success">Submit</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

templates/autoencoder/autoencode_cases.html
{% extends 'base.html' %}

{% block title %}
    Your auto-encoded cases
{% endblock %}
{% block head %}
    <style>
        .display-flex {
            display: flex;
            justify-content: center;
            flex-direction: row;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="d-flex justify-content-center">
        <div>
            <div class="display-flex" style="justify-content: space-evenly">
                <a href="{% url 'main:main' %}" class="btn btn-info">Back to main menu</a>
                <h3>You have encoded: {{ case_list|length }}</h3>
            </div>
            {% for case in case_list %}
                <div class="card display-flex p-3">
                    <div>
                        <h6>Original</h6>
                        <img src="{{ case.original.url }}" width="270" height="235" alt="">
                    </div>
                    <div>
                        <h6>Encoded</h6>
                        <img src="{{ case.encoded.url }}" width="270" height="235" alt="">
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Machine learning
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    {% block head %}

    {% endblock %}
    <style>
        .green-bg {
            background-color: greenyellow;
        }

    </style>
</head>
<body class="green-bg">
{% block content %}

{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/main.html
{% extends 'base.html' %}
{% block head %}
    <style>
        .child {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
{% endblock %}
{% block content %}
    <div class="d-relative">
        <div class="card p-3 text-center child">
            <ul>
                <li><a href="{% url 'users:profile' %}">Profile</a></li>
                <li><a href="{% url 'autoencoder:autoencode' %}">Auto-encode image</a></li>
                <li><a href="{% url 'autoencoder:cases' %}">Your auto-encoded images</a></li>
                <li><a href="{% url 'users:logout' %}">Logout</a></li>
            </ul>
        </div>
    </div>
{% endblock %}